name: build and deploy static pages by dotnet
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    strategy:
      matrix:
        dotnet-version: [ '10.0.x' ]
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      # build job
      - name: checkout
        uses: actions/checkout@v6
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: create html builder
        run: dotnet build -c Release tools/builder/
      - name: run html builder
        run: ./tools/builder/build/bin/Release/net10.0/build
    # run test
      - name: Run unit test
        run: dotnet test ./tools/builder/builder.slnx --no-build -c Release
    #deploy page
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'page-output'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
